// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Saic.Models;

#nullable disable

namespace Saic.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20250502103937_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Saic.Models.Ad", b =>
                {
                    b.Property<Guid>("AdID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdNome")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("AdObs")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("AdTiers")
                        .HasColumnType("bit");

                    b.Property<Guid>("CoopID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DCPrimarioID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DCSecundarioID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastChange")
                        .HasColumnType("datetime2");

                    b.HasKey("AdID");

                    b.HasIndex("CoopID");

                    b.HasIndex("DCPrimarioID");

                    b.HasIndex("DCSecundarioID");

                    b.ToTable("Ads");
                });

            modelBuilder.Entity("Saic.Models.AuxiliarModels.Fabricante", b =>
                {
                    b.Property<int>("FabricanteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FabricanteID"));

                    b.Property<string>("FabricanteNome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("FabricanteTipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("FabricanteID");

                    b.ToTable("Fabricantes");
                });

            modelBuilder.Entity("Saic.Models.AuxiliarModels.SistOp", b =>
                {
                    b.Property<int>("SistOpID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SistOpID"));

                    b.Property<DateTime>("ServidorSuporte")
                        .HasColumnType("datetime2");

                    b.Property<string>("SistOpNome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SistOpID");

                    b.ToTable("SistOps");
                });

            modelBuilder.Entity("Saic.Models.AuxiliarModels.TipoAuxiliar", b =>
                {
                    b.Property<int>("TipoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TipoID"));

                    b.Property<string>("TipoCategoria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TipoNome")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("TipoID");

                    b.ToTable("TipoAuxiliares");
                });

            modelBuilder.Entity("Saic.Models.Coop", b =>
                {
                    b.Property<Guid>("CoopID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Adesao")
                        .HasColumnType("datetime2");

                    b.Property<string>("CoopCidade")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("CoopNome")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("CoopNumero")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<DateTime>("LastChange")
                        .HasColumnType("datetime2");

                    b.Property<int?>("QtdCompts")
                        .HasColumnType("int");

                    b.Property<Guid?>("RespID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CoopID");

                    b.HasIndex("RespID");

                    b.ToTable("Coops");
                });

            modelBuilder.Entity("Saic.Models.Firewall", b =>
                {
                    b.Property<Guid>("FirewallID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CoopID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FabricanteID")
                        .HasColumnType("int");

                    b.Property<bool>("FirewallBackup")
                        .HasColumnType("bit");

                    b.Property<string>("FirewallModelo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("FirewallObs")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("FirewallSerial")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("LastChange")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("UnidadeID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("FirewallID");

                    b.HasIndex("CoopID");

                    b.HasIndex("FabricanteID");

                    b.HasIndex("UnidadeID");

                    b.ToTable("Firewalls");
                });

            modelBuilder.Entity("Saic.Models.Link", b =>
                {
                    b.Property<Guid>("LinkID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastChange")
                        .HasColumnType("datetime2");

                    b.Property<string>("LinkIP")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("LinkObs")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("LinkProvedor")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("TipoLinkID")
                        .HasColumnType("int");

                    b.Property<Guid>("UnidadeID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LinkID");

                    b.HasIndex("TipoLinkID");

                    b.HasIndex("UnidadeID");

                    b.ToTable("Links");
                });

            modelBuilder.Entity("Saic.Models.RespCoop", b =>
                {
                    b.Property<Guid>("RespID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastChange")
                        .HasColumnType("datetime2");

                    b.Property<string>("RespNome")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("RespID");

                    b.ToTable("RespCoops");
                });

            modelBuilder.Entity("Saic.Models.Servidor", b =>
                {
                    b.Property<Guid>("ServidorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CoopID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("FabricanteID")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastChange")
                        .HasColumnType("datetime2");

                    b.Property<string>("ServidorAcesso")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<DateTime?>("ServidorGarantia")
                        .HasColumnType("datetime2");

                    b.Property<string>("ServidorIDrac")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("ServidorIP")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("ServidorModelo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("ServidorNome")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("ServidorObs")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("ServidorRAM")
                        .HasColumnType("int");

                    b.Property<string>("ServidorSerial")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<bool>("ServidorVirtual")
                        .HasColumnType("bit");

                    b.Property<int>("SistOpID")
                        .HasColumnType("int");

                    b.Property<Guid>("UnidadeID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ServidorID");

                    b.HasIndex("CoopID");

                    b.HasIndex("FabricanteID");

                    b.HasIndex("SistOpID");

                    b.HasIndex("UnidadeID");

                    b.ToTable("Servidores");
                });

            modelBuilder.Entity("Saic.Models.Switch", b =>
                {
                    b.Property<Guid>("SwitchID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CoopID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FabricanteID")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastChange")
                        .HasColumnType("datetime2");

                    b.Property<string>("SwitchAcesso")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<bool>("SwitchBackup")
                        .HasColumnType("bit");

                    b.Property<string>("SwitchModelo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("SwitchObs")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("SwitchPortas")
                        .HasColumnType("int");

                    b.Property<string>("SwitchSerial")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<Guid?>("UnidadeID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SwitchID");

                    b.HasIndex("CoopID");

                    b.HasIndex("FabricanteID");

                    b.HasIndex("UnidadeID");

                    b.ToTable("Switches");
                });

            modelBuilder.Entity("Saic.Models.Unidade", b =>
                {
                    b.Property<Guid>("UnidadeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CoopID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastChange")
                        .HasColumnType("datetime2");

                    b.Property<string>("UnidadeNome")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("UnidadeNumero")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("UnidadeObs")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("UnidadeID");

                    b.HasIndex("CoopID");

                    b.ToTable("Unidades");
                });

            modelBuilder.Entity("Saic.Models.Vlan", b =>
                {
                    b.Property<Guid>("VlanID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("LastChange")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UnidadeID")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("VlanNome")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("VlanObs")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("VlanRangeIP")
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("VlanTag")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("VlanID");

                    b.HasIndex("UnidadeID");

                    b.ToTable("Vlans");
                });

            modelBuilder.Entity("Saic.Models.Ad", b =>
                {
                    b.HasOne("Saic.Models.Coop", "Coop")
                        .WithMany()
                        .HasForeignKey("CoopID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Saic.Models.Servidor", "DCPrimario")
                        .WithMany()
                        .HasForeignKey("DCPrimarioID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Saic.Models.Servidor", "DCSecundario")
                        .WithMany()
                        .HasForeignKey("DCSecundarioID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Coop");

                    b.Navigation("DCPrimario");

                    b.Navigation("DCSecundario");
                });

            modelBuilder.Entity("Saic.Models.Coop", b =>
                {
                    b.HasOne("Saic.Models.RespCoop", "RespCoop")
                        .WithMany("Coops")
                        .HasForeignKey("RespID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("RespCoop");
                });

            modelBuilder.Entity("Saic.Models.Firewall", b =>
                {
                    b.HasOne("Saic.Models.Coop", "Coop")
                        .WithMany("Firewalls")
                        .HasForeignKey("CoopID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Saic.Models.AuxiliarModels.Fabricante", "Fabricante")
                        .WithMany()
                        .HasForeignKey("FabricanteID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Saic.Models.Unidade", "Unidade")
                        .WithMany("Firewalls")
                        .HasForeignKey("UnidadeID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Coop");

                    b.Navigation("Fabricante");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("Saic.Models.Link", b =>
                {
                    b.HasOne("Saic.Models.AuxiliarModels.TipoAuxiliar", "TipoLink")
                        .WithMany()
                        .HasForeignKey("TipoLinkID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Saic.Models.Unidade", "Unidade")
                        .WithMany("Links")
                        .HasForeignKey("UnidadeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoLink");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("Saic.Models.Servidor", b =>
                {
                    b.HasOne("Saic.Models.Coop", "Coop")
                        .WithMany("Servidores")
                        .HasForeignKey("CoopID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Saic.Models.AuxiliarModels.Fabricante", "Fabricante")
                        .WithMany()
                        .HasForeignKey("FabricanteID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Saic.Models.AuxiliarModels.SistOp", "SistOp")
                        .WithMany()
                        .HasForeignKey("SistOpID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Saic.Models.Unidade", "Unidade")
                        .WithMany("Servidores")
                        .HasForeignKey("UnidadeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Coop");

                    b.Navigation("Fabricante");

                    b.Navigation("SistOp");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("Saic.Models.Switch", b =>
                {
                    b.HasOne("Saic.Models.Coop", "Coop")
                        .WithMany("Switches")
                        .HasForeignKey("CoopID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Saic.Models.AuxiliarModels.Fabricante", "Fabricante")
                        .WithMany()
                        .HasForeignKey("FabricanteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Saic.Models.Unidade", "Unidade")
                        .WithMany("Switches")
                        .HasForeignKey("UnidadeID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Coop");

                    b.Navigation("Fabricante");

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("Saic.Models.Unidade", b =>
                {
                    b.HasOne("Saic.Models.Coop", "Coop")
                        .WithMany("Unidades")
                        .HasForeignKey("CoopID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Coop");
                });

            modelBuilder.Entity("Saic.Models.Vlan", b =>
                {
                    b.HasOne("Saic.Models.Unidade", "Unidade")
                        .WithMany("Vlans")
                        .HasForeignKey("UnidadeID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Unidade");
                });

            modelBuilder.Entity("Saic.Models.Coop", b =>
                {
                    b.Navigation("Firewalls");

                    b.Navigation("Servidores");

                    b.Navigation("Switches");

                    b.Navigation("Unidades");
                });

            modelBuilder.Entity("Saic.Models.RespCoop", b =>
                {
                    b.Navigation("Coops");
                });

            modelBuilder.Entity("Saic.Models.Unidade", b =>
                {
                    b.Navigation("Firewalls");

                    b.Navigation("Links");

                    b.Navigation("Servidores");

                    b.Navigation("Switches");

                    b.Navigation("Vlans");
                });
#pragma warning restore 612, 618
        }
    }
}
