// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Saic.Models;

#nullable disable

namespace Saic.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    partial class StoreDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Saic.Models.Coop", b =>
                {
                    b.Property<Guid>("CoopID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Adesao")
                        .HasColumnType("datetime2");

                    b.Property<string>("CoopCidade")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("CoopNome")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("CoopNumero")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<int?>("QtdCompts")
                        .HasColumnType("int");

                    b.Property<Guid?>("RespID")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CoopID");

                    b.HasIndex("RespID");

                    b.ToTable("Coops");
                });

            modelBuilder.Entity("Saic.Models.RespCoop", b =>
                {
                    b.Property<Guid>("RespID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RespEquipe")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("RespNome")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("RespID");

                    b.ToTable("RespCoops");
                });

            modelBuilder.Entity("Saic.Models.Coop", b =>
                {
                    b.HasOne("Saic.Models.RespCoop", "RespCoop")
                        .WithMany("Coops")
                        .HasForeignKey("RespID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("RespCoop");
                });

            modelBuilder.Entity("Saic.Models.RespCoop", b =>
                {
                    b.Navigation("Coops");
                });
#pragma warning restore 612, 618
        }
    }
}
